export type {
  Id,
  Doc,
  DataModel,
  TableNames,
} from "./convex/_generated/dataModel";
export type { BackgroundAgentEntry } from "./convex/_validators/tableFields";
export { api, internal } from "./convex/_generated/api";
export {
  AI_MODEL_OPTIONS,
  CLAUDE_MODELS,
  CODEX_MODELS,
  DEFAULT_AI_MODEL,
  CODEX_AUTH_ENV_KEYS,
  CODEX_CONFIG_ENV_KEYS,
  OPENCODE_AUTH_ENV_KEYS,
  CURSOR_AUTH_ENV_KEYS,
  PROVIDER_PRIMARY_AUTH_KEY,
  findAIModelOption,
  getAIProviderAvailability,
  getAIModelProvider,
  getVisibleAIModelOptions,
  getModelTraits,
  resolveReasoningLevel,
  resolveTraitsForDisplay,
  buildTraitsExecutionPayload,
  modelHasTraits,
  getReasoningLevelLabel,
  hasCodexAuthEnvVar,
  normalizeAIModel,
  REASONING_LEVELS,
  DEFAULT_REASONING_LEVEL,
  modelTraitsExecutionFields,
  type AIModel,
  type AIModelOption,
  type AIProvider,
  type AIProviderAvailability,
  type ReasoningLevel,
  type ModelTraits,
  type StoredModelTraits,
  type ModelTraitsExecutionArgs,
  PERSONALISATION_PRESETS,
} from "./convex/validators";
